# Generated by Django 6.0.2 on 2026-02-28 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InjectionInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_quantity",
                    models.IntegerField(default=0, verbose_name="当前库存"),
                ),
                (
                    "updated_quantity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="更新后库存"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injection_inventory",
                        to="data.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "注塑库存",
                "verbose_name_plural": "注塑库存",
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_quantity",
                    models.IntegerField(default=0, verbose_name="当前库存"),
                ),
                (
                    "updated_quantity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="更新后库存"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="data.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "涂装库存",
                "verbose_name_plural": "涂装库存",
            },
        ),
        migrations.CreateModel(
            name="SafetyStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, verbose_name="安全库存数量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_stock",
                        to="data.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "安全库存",
                "verbose_name_plural": "安全库存",
            },
        ),
    ]
