# Generated by Django 6.0.2 on 2026-02-28 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_injectioninventory_inventory_safetystock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="injectioninventory",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "注塑库存",
                "verbose_name_plural": "注塑库存",
            },
        ),
        migrations.AlterModelOptions(
            name="inventory",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "涂装库存",
                "verbose_name_plural": "涂装库存",
            },
        ),
        migrations.AlterModelOptions(
            name="safetystock",
            options={
                "ordering": ["product"],
                "verbose_name": "安全库存",
                "verbose_name_plural": "安全库存",
            },
        ),
        migrations.AlterField(
            model_name="injectioninventory",
            name="current_quantity",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="当前库存",
            ),
        ),
        migrations.AlterField(
            model_name="injectioninventory",
            name="updated_quantity",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="更新后库存",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="current_quantity",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="当前库存",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="updated_quantity",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="更新后库存",
            ),
        ),
        migrations.AlterField(
            model_name="safetystock",
            name="quantity",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="安全库存数量",
            ),
        ),
    ]
