# Generated by Django 6.0.2 on 2026-02-28 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_alter_injectioninventory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssemblyPullData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="顺序号")),
                ("planned_time", models.DateTimeField(verbose_name="计划时间")),
                (
                    "import_batch",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="导入批次"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assembly_data",
                        to="data.color",
                        verbose_name="颜色",
                    ),
                ),
                (
                    "vehicle_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assembly_data",
                        to="data.vehiclemodel",
                        verbose_name="车型",
                    ),
                ),
            ],
            options={
                "verbose_name": "总成拉动数据",
                "verbose_name_plural": "总成拉动数据",
                "ordering": ["sequence"],
                "indexes": [
                    models.Index(
                        fields=["sequence"], name="data_assemb_sequenc_f3beb6_idx"
                    ),
                    models.Index(
                        fields=["import_batch"], name="data_assemb_import__9d6c74_idx"
                    ),
                ],
            },
        ),
    ]
