# Generated by Django 6.0.2 on 2026-02-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_assemblypulldata"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "param_key",
                    models.CharField(
                        choices=[
                            ("CYCLE_TIME_MIN", "涂装一圈时间(分钟)"),
                            ("AVG_HANGING_COUNT", "每车平均挂数"),
                            ("TOTAL_VEHICLES", "涂装线一圈车数"),
                            ("SHORT_TERM_CAPACITY", "短期产能百分比(%)"),
                            ("LONG_TERM_CAPACITY", "长期产能百分比(%)"),
                            ("FRONT_REAR_BALANCE_D", "前后平衡约束差值"),
                            ("GROUP_CAPACITY_LIMIT", "组车数平衡约束(%)"),
                            ("LONG_TERM_FORECAST_HOURS", "长期需求预测时间(小时)"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="参数键",
                    ),
                ),
                (
                    "param_value",
                    models.CharField(max_length=200, verbose_name="参数值"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统参数",
                "verbose_name_plural": "系统参数",
            },
        ),
    ]
