# Generated by Django 6.0.2 on 2026-02-28 03:43

from django.db import migrations


def create_default_parameters(apps, schema_editor):
    SystemParameter = apps.get_model('data', 'SystemParameter')
    parameters = [
        ('CYCLE_TIME_MIN', '300', '涂装一圈到落库需要的时间（分钟）'),
        ('AVG_HANGING_COUNT', '4', '每车挂具的平均挂数'),
        ('TOTAL_VEHICLES', '100', '涂装线一圈一共多少台车'),
        ('SHORT_TERM_CAPACITY', '40', '涂装线一圈短期产能百分比(%)'),
        ('LONG_TERM_CAPACITY', '60', '涂装线一圈长期产能百分比(%)'),
        ('FRONT_REAR_BALANCE_D', '15', '长期前后平衡约束差值'),
        ('GROUP_CAPACITY_LIMIT', '40', '组车数平衡约束(%)'),
        ('LONG_TERM_FORECAST_HOURS', '2', '长期需求预测时间(小时)'),
    ]
    for key, value, desc in parameters:
        SystemParameter.objects.get_or_create(
            param_key=key,
            defaults={'param_value': value, 'description': desc}
        )


def reverse_parameters(apps, schema_editor):
    SystemParameter = apps.get_model('data', 'SystemParameter')
    SystemParameter.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_systemparameter"),
    ]

    operations = [
        migrations.RunPython(create_default_parameters, reverse_parameters),
    ]
