# Generated by Django 6.0.2 on 2026-03-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_init_system_parameters"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("inventory", "涂装库存"),
                            ("injection", "注塑库存"),
                            ("safety", "安全库存"),
                            ("assembly", "总成拉动"),
                        ],
                        max_length=20,
                        verbose_name="导入类型",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("partial", "部分成功"),
                            ("failed", "失败"),
                        ],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("message", models.CharField(max_length=255, verbose_name="结果说明")),
                (
                    "success_count",
                    models.PositiveIntegerField(default=0, verbose_name="成功条数"),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(default=0, verbose_name="失败条数"),
                ),
                (
                    "error_details",
                    models.JSONField(blank=True, default=list, verbose_name="错误明细"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "导入记录",
                "verbose_name_plural": "导入记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
