# Generated by Django 6.0.2 on 2026-03-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0007_importrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="injectioninventory",
            name="update_time",
        ),
        migrations.RemoveField(
            model_name="injectioninventory",
            name="updated_quantity",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="update_time",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="updated_quantity",
        ),
    ]
