# Generated by Django 6.0.2 on 2026-02-28 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data", "0006_init_system_parameters"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "short_term_duration",
                    models.IntegerField(verbose_name="短期时长(分钟)"),
                ),
                (
                    "long_term_duration",
                    models.IntegerField(verbose_name="长期时长(分钟)"),
                ),
                ("total_vehicles", models.IntegerField(verbose_name="总车数")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "计算中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "cycle_time_min",
                    models.IntegerField(verbose_name="涂装一圈时间(分钟)"),
                ),
                ("avg_hanging_count", models.IntegerField(verbose_name="每车平均挂数")),
                (
                    "total_vehicles_in_line",
                    models.IntegerField(verbose_name="涂装线一圈车数"),
                ),
                (
                    "short_term_capacity",
                    models.FloatField(verbose_name="短期产能百分比"),
                ),
                (
                    "long_term_capacity",
                    models.FloatField(verbose_name="长期产能百分比"),
                ),
                (
                    "front_rear_balance_d",
                    models.IntegerField(verbose_name="前后平衡约束差值"),
                ),
                (
                    "group_capacity_limit",
                    models.FloatField(verbose_name="组车数平衡约束"),
                ),
            ],
            options={
                "verbose_name": "排产记录",
                "verbose_name_plural": "排产记录",
                "ordering": ["-record_time"],
            },
        ),
        migrations.CreateModel(
            name="SchedulePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("short", "短期"), ("long", "长期")],
                        max_length=20,
                        verbose_name="计划类型",
                    ),
                ),
                ("vehicle_count", models.IntegerField(verbose_name="生产车数")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.product",
                        verbose_name="产品",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="schedule.schedulerecord",
                        verbose_name="排产记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "排产计划",
                "verbose_name_plural": "排产计划",
            },
        ),
        migrations.CreateModel(
            name="RiskRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_type",
                    models.CharField(
                        choices=[("short", "短期"), ("long", "长期")],
                        max_length=20,
                        verbose_name="风险类型",
                    ),
                ),
                ("final_value", models.IntegerField(verbose_name="终值")),
                ("safety_stock", models.IntegerField(verbose_name="安全库存")),
                (
                    "risk_value",
                    models.IntegerField(blank=True, null=True, verbose_name="风险值"),
                ),
                (
                    "group_risk_value",
                    models.IntegerField(blank=True, null=True, verbose_name="组风险值"),
                ),
                (
                    "rank",
                    models.IntegerField(blank=True, null=True, verbose_name="排名"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.product",
                        verbose_name="产品",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="schedule.schedulerecord",
                        verbose_name="排产记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "风险记录",
                "verbose_name_plural": "风险记录",
                "ordering": ["record", "risk_type", "rank"],
            },
        ),
        migrations.CreateModel(
            name="FormationSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_number", models.IntegerField(verbose_name="槽位号")),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("short", "短期"), ("long", "长期")],
                        max_length=20,
                        verbose_name="计划类型",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.product",
                        verbose_name="产品",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formation_slots",
                        to="schedule.schedulerecord",
                        verbose_name="排产记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "阵型槽位",
                "verbose_name_plural": "阵型槽位",
                "ordering": ["slot_number"],
                "unique_together": {("record", "slot_number")},
            },
        ),
        migrations.CreateModel(
            name="DemandRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "demand_type",
                    models.CharField(
                        choices=[("short", "短期"), ("long", "长期")],
                        max_length=20,
                        verbose_name="需求类型",
                    ),
                ),
                ("demand_quantity", models.IntegerField(verbose_name="需求数量(台)")),
                (
                    "production_quantity",
                    models.IntegerField(verbose_name="生产数量(台)"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.product",
                        verbose_name="产品",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demands",
                        to="schedule.schedulerecord",
                        verbose_name="排产记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "需求记录",
                "verbose_name_plural": "需求记录",
                "unique_together": {("record", "product", "demand_type")},
            },
        ),
    ]
