# Generated by Django 6.0.2 on 2026-03-23 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_init_system_parameters"),
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formationslot",
            name="is_reused",
            field=models.BooleanField(default=False, verbose_name="是否复用上一轮槽位"),
        ),
        migrations.AddField(
            model_name="scheduleplan",
            name="note",
            field=models.CharField(blank=True, max_length=255, verbose_name="计划说明"),
        ),
        migrations.CreateModel(
            name="InventorySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inventory_type",
                    models.CharField(
                        choices=[("paint", "涂装库存"), ("injection", "注塑库存")],
                        max_length=20,
                        verbose_name="库存类型",
                    ),
                ),
                ("current_quantity", models.IntegerField(verbose_name="计算前库存")),
                ("delta_quantity", models.IntegerField(verbose_name="库存变动")),
                ("updated_quantity", models.IntegerField(verbose_name="更新后库存")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.product",
                        verbose_name="产品",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_snapshots",
                        to="schedule.schedulerecord",
                        verbose_name="排产记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存快照",
                "verbose_name_plural": "库存快照",
                "ordering": ["inventory_type", "product"],
            },
        ),
    ]
