# Generated by Django 6.0.2 on 2026-03-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_formationslot_is_reused_scheduleplan_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "计算中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                    ("rolled_back", "已回退"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
